# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-25 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text=b'URL video', null=True, verbose_name=b'Video'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_published',
            field=models.BooleanField(default=b''),
        ),
    ]
