# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20161125_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tree_id', 'level', 'ordering'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering'),
        ),
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=b'', verbose_name=b'Published'),
        ),
    ]
