# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 13:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20161125_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=b'Support Title')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text=b'URL video', null=True, verbose_name=b'Video')),
                ('video_published', models.BooleanField(default=b'')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'Url')),
                ('slogan', models.CharField(max_length=250, verbose_name=b'Support Slogan')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'Short text')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'Full text')),
                ('published', models.BooleanField(verbose_name=b'Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering')),
            ],
            options={
                'ordering': ['ordering'],
                'db_table': 'support',
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tree_id', 'level'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='support',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='product.Category', verbose_name=b'Categories'),
        ),
        migrations.AddField(
            model_name='support',
            name='tag',
            field=models.ManyToManyField(related_name='support_tags', related_query_name=b'support_tags', to='product.Tag', verbose_name=b'Tags'),
        ),
    ]
