# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20161128_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Name')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'Url')),
                ('published', models.BooleanField(verbose_name=b'Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name=b'Product')),
            ],
            options={
                'ordering': ['ordering'],
                'db_table': 'menuItemsProducts',
                'verbose_name': 'Product',
                'verbose_name_plural': 'Menu Items for Products',
            },
        ),
    ]
