# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_category_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='category',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='content.Category', verbose_name=b'Category'),
        ),
    ]
